name = "message-board"
main = "src/index.ts"
compatibility_date = "2025-12-31"

[[d1_databases]]
binding = "DB"
database_name = "message-board-db"
database_id = "00000000-0000-0000-0000-000000000000" # ローカル用ダミーID
